spring:
  application:
    name: boot
  datasource:
    url: jdbc:postgresql://localhost:5432/Auth
    driverClassName: org.postgresql.Driver
    username: postgres
    password: qwerty12356
  jpa:
    hibernate:
      ddl-auto: create

car:
  config:
    maxCars: 5
    sortBy: mark,model,yearOfManufacture

sources:


loan:
  minimalincome: 40000
  minumalcarcost: 1000000